name: Shopify 2.0 CI Theme Deployment

on:
  push:
    branches:
      - main
      - next

jobs:
  deploy-next:
    if: github.ref == 'refs/heads/next'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install -g @shopify/cli

      - name: push to preview theme
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_FLAG_STORE }}
          SHOPIFY_THEME_DEV_ID: ${{ secrets.SHOPIFY_THEME_DEV_ID }}
          SHOPIFY_FLAG_FORCEN: 1
        run: |
          shopify theme push \
            --store "$SHOPIFY_FLAG_STORE" \
            --token "$SHOPIFY_CLI_THEME_TOKEN" \
            --theme "$SHOPIFY_THEME_DEV_ID"

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g @shopify/cli
      - name: push to live theme demo store
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_FLAG_STORE }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
          SHOPIFY_FLAG_FORCEN: 1
        run: |
          shopify theme push \
            --store "$SHOPIFY_FLAG_STORE" \
            --token "$SHOPIFY_CLI_THEME_TOKEN" \
            --theme "$SHOPIFY_THEME_ID" \
            --allow-live
